spring.application.name=Smart-Stock

app.client-id=${APP_CLIENT_ID:ABC}
app.client-secret=${APP_CLIENT_SECRET:DEF}

api.auth-url=http://localhost:3000

spring.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=smartstockdb
spring.mongodb.username=admin
spring.mongodb.password=123
