services:
  mysql:
    container_name: mysql-db-customer-connect
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=customer_connect_db
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    ports:
      - "3306:3306"